# Generated by Django 3.2.9 on 2021-12-19 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
